name: Post coverage comment

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: ["pytest"]
    types:
      - completed

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@7188638f871f721a365d644f505d1ff3df20d683 # v3.40
        with:
          ANNOTATE_MISSING_LINES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
